require 'cocoapods-catalyst-support'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

use_frameworks!

target 'Sample' do
  pod 'Firebase/Analytics'
  pod 'TFBase', :path => 'Libraries/TFBase' # this does nothing but depend on 'Firebase/Analytics' -- if you comment it out, macCatalyst build works
end

#Configure your macCatalyst dependencies
catalyst_configuration do
	# Uncomment the next line for a verbose output
	# verbose!

  ios 'Firebase/Analytics'
end

#Configure your macCatalyst App
post_install do |installer|
	installer.configure_catalyst
end
